package com.consultas.SistemaConsultas.Auth;

public class MessageHTML {
	public static final String TEMPLATE_PRUEBA = "<html lang=\"en\">\n"
			+ "  <head>\n"
			+ "    <meta charset=\"utf-8\" >\n"
			+ "    <style>\n"
			+ "      .bg{ \n"
			+ "      width:100%; background: white; \n"
			+ "      }\n"
			+ "      .cont{\n"
			+ "      width:600px; margin:0 auto; background: white; \n"
			+ "      }\n"
			+ "      .boxCont{width:70%; margin:0 auto;}\n"
			+ "      .boxCont p{\n"
			+ "      font-size:18px; color: black;\n"
			+ "      }\n"
			+ "      .boxCode{text-align: center; border-radius: 10px; background-color: aquamarine; font-size: 16px; padding: auto;}\n"
			+ "      .boxCode p{width:12%; height: 40px; font-size: 16px; display: inline-block ; border-bottom: 1px beige; \n"
			+ "      border-radius: 5px; text-align: center; font-size: 32px; margin-left: 5px; color: antiquewhite; }\n"
			+ "       .boxCont .footer{ font-size: 12px; color: gray; text-align: center}\n"
			+ "        .cont .fo{\n"
			+ "          width: 100%;\n"
			+ "          height: 10px;\n"
			+ "          margin: 20px 0 0 0;\n"
			+ "          background: linear-gradient(90deg, #4155c4, #1b04a1);\n"
			+ "        }\n"
			+ "    </style>\n"
			+ "  </head>\n"
			+ "  <body>\n"
			+ "    <div class=\"bg\">\n"
			+ "      <div class=\"cont\">\n"
			+ "        <div class=\"boxCont\">\n"
			+ "          <p> <strong>Estimado Usuario</strong></p>\n"
			+ "          <p> Su codigo de verificacion para el inicio de sesion es: </p>\n"
			+ "            <div class=\"boxCode\">\n"
			+ "                <p>{0}</p>\n"
			+ "                <p>{1}</p>\n"
			+ "                <p>{2}</p>\n"
			+ "                <p>{3}</p>\n"
			+ "                <p>{4}</p>\n"
			+ "                <p>{5}</p>\n"
			+ "            </div>\n"
			+ "            <p> Este codigo es de un solo uso.</p>\n"
			+ "            <br>\n"
			+ "             <p>Comprobar cuenta: <a href=\"localhost:3000/confirmar/\">Haga Click Aqui...</a></p>"
			+ "             <p class=\"footer\">Este mensaje de correo electronico se ha enviado desde \n"
			+ "              una direccion exclusivamente para envios. No responda este mensaje\n"
			+ "            </p>\n"
			+ "        </div>\n"
			+ "      </div>\n"
			+ "    </div>\n"
			+ "  </body>\n"
			+ "</html>"
			+ "";
}
